<?php
/**
 * @category  Y1
 * @package   Y1_GoogleAddressValidation
 * @copyright Copyright (c) Y1 Digital AG (https://y1.de)
 * @contact   ronak.chauhan@y1.de
 *
 * @var $block \Magento\Framework\View\Element\Template
 * @var $viewModel \Y1\GoogleAddressValidation\ViewModel\Autocomplete
 */

$viewModel = $block->getData('view_model');
?>
<script type="text/x-magento-init">
<?= $block->getJsLayout()?>
</script>
